# Generated by Django 3.2.13 on 2022-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0003_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationAvail',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Confirmed')], default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
