# Generated by Django 3.2.13 on 2022-05-18 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0004_auto_20220518_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
