# Generated by Django 3.2.13 on 2022-05-10 14:26

import cloudinary.models
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='EditFlavours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=150)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('allergens', models.TextField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
