# Generated by Django 3.2.13 on 2022-05-16 14:03

import cloudinary.models
import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=120)),
                ('image', cloudinary.models.CloudinaryField(default=None, max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='image')),
                ('image_alternative_text', models.TextField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name_plural': 'About Statement',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.BigIntegerField(blank=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('order_ranking', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['order_ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=120)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('allergens', models.TextField(max_length=60)),
                ('display_flavour', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Display')], default=0)),
                ('order_ranking', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['order_ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='static/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'verbose_name_plural': 'Upload PDF Menu',
            },
        ),
        migrations.CreateModel(
            name='Nybro23Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('image', cloudinary.models.CloudinaryField(default=None, max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='image')),
                ('image_alternative_text', models.TextField(blank=True, max_length=120)),
                ('order_ranking', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['order_ranking'],
            },
        ),
        migrations.CreateModel(
            name='Nybro23Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Nybrogatan 23 Content',
            },
        ),
    ]
