# Generated by Django 3.2.13 on 2022-05-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditAbout',
            new_name='About',
        ),
        migrations.RenameModel(
            old_name='EditFlavours',
            new_name='Flavour',
        ),
    ]
