# Generated by Django 3.2.13 on 2022-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20220510_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='allergens',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='category',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='description',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
