# Generated by Django 3.2.13 on 2022-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20220511_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='allergens',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='description',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
