# Generated by Django 3.2.13 on 2022-05-20 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20220520_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupdf',
            name='pdf',
            field=models.FileField(upload_to='media/static/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
