# Generated by Django 3.2.13 on 2022-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_alter_about_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
