# Generated by Django 3.2.13 on 2022-05-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_auto_20220511_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='static/pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
