# Generated by Django 3.2.13 on 2022-05-12 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_menupdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Statement'},
        ),
        migrations.AlterModelOptions(
            name='menupdf',
            options={'verbose_name': 'Upload PDF Menu'},
        ),
        migrations.AlterField(
            model_name='menupdf',
            name='pdf',
            field=models.FileField(upload_to='static/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
