# Generated by Django 3.2.13 on 2022-05-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_auto_20220512_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Statement'},
        ),
        migrations.AlterModelOptions(
            name='menupdf',
            options={'verbose_name_plural': 'Upload PDF Menu'},
        ),
    ]
