# Generated by Django 3.2.13 on 2022-05-12 10:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
