# Generated by Django 3.2.13 on 2022-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='order_num',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
