# Generated by Django 3.2.13 on 2022-05-13 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_flavour_order_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavour',
            options={'ordering': ['order_ranking', 'name']},
        ),
        migrations.RemoveField(
            model_name='flavour',
            name='order_num',
        ),
        migrations.AddField(
            model_name='flavour',
            name='display_flavour',
            field=models.IntegerField(choices=[(0, 'Hidden'), (1, 'Display')], default=0),
        ),
        migrations.AddField(
            model_name='flavour',
            name='order_ranking',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
