# Generated by Django 3.2.13 on 2022-05-13 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_auto_20220513_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order_ranking', 'name']},
        ),
        migrations.AddField(
            model_name='contact',
            name='order_ranking',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
