# Generated by Django 3.2.13 on 2022-05-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_auto_20220513_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nybrogatan23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Nybrogatan 23 content',
            },
        ),
    ]
