# Generated by Django 3.2.13 on 2022-05-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_nybrogatan23'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nybrogatan23',
            new_name='Nybro23Text',
        ),
    ]
