# Generated by Django 3.2.13 on 2022-05-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_rename_nybrogatan23_nybro23text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nybro23text',
            options={'verbose_name_plural': 'Nybrogatan 23 Content'},
        ),
    ]
