# Generated by Django 3.2.13 on 2022-05-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_nybro23images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nybro23Images',
            new_name='Nybro23Image',
        ),
        migrations.AlterModelOptions(
            name='nybro23image',
            options={'ordering': ['order_ranking', 'name']},
        ),
    ]
