# Generated by Django 3.2.13 on 2022-05-14 16:13

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApp', '0021_auto_20220514_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_alternative_text',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='nybro23image',
            name='image_alternative_text',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='nybro23image',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.flavour')),
            ],
        ),
    ]
