# Generated by Django 3.2.13 on 2022-05-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0022_auto_20220514_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nybro23image',
            options={'ordering': ['order_ranking']},
        ),
    ]
