# Generated by Django 3.2.13 on 2022-05-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0023_alter_nybro23image_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
